// <auto-generated />
using EFCore.Migrations.CustomSql.Tests.MigrationTests.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.Migrations.CustomSql.Tests.MigrationTests.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerMigrationDbContext))]
<<<<<<<< HEAD:tests/EFCore.Migrations.CustomSql.Tests/MigrationTests/SqlServer/Migrations/20260430193309_Initial.Designer.cs
<<<<<<<< HEAD:tests/EFCore.Migrations.CustomSql.Tests/MigrationTests/SqlServer/Migrations/20260430193309_Initial.Designer.cs
<<<<<<<< HEAD:tests/EFCore.Migrations.CustomSql.Tests/MigrationTests/SqlServer/Migrations/20260430193309_Initial.Designer.cs
    [Migration("20260430193309_Initial")]
========
    [Migration("20260501195634_Initial")]
>>>>>>>> 9de0344 (Updated annotation key in snapshot.):tests/EFCore.Migrations.CustomSql.Tests/MigrationTests/SqlServer/Migrations/20260501195634_Initial.Designer.cs
========
    [Migration("20260501205054_Initial")]
>>>>>>>> 879653f (Moved EFCore.Migrations.Functions, EFCore.Migrations.Triggers, EFCore.Migrations.Views to):tests/EFCore.Migrations.CustomSql.Tests/MigrationTests/SqlServer/Migrations/20260501205054_Initial.Designer.cs
========
    [Migration("20260502133426_Initial")]
>>>>>>>> c1c7fe6 (Updated ModelBuilderExtensions.):tests/EFCore.Migrations.CustomSql.Tests/MigrationTests/SqlServer/Migrations/20260502133426_Initial.Designer.cs
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
<<<<<<<< HEAD:tests/EFCore.Migrations.CustomSql.Tests/MigrationTests/SqlServer/Migrations/20260430193309_Initial.Designer.cs
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Sql:Custom:get_blog_name:Down", "DROP PROCEDURE IF EXISTS [get_blog_name]")
                .HasAnnotation("Sql:Custom:get_blog_name:Up", "CREATE OR ALTER PROCEDURE [get_blog_name] @id INT AS SELECT [Name] FROM [Blogs] WHERE [Id] = @id");
========
                .HasAnnotation("CustomSql:Raw:get_blog_name:Down", "DROP PROCEDURE IF EXISTS [get_blog_name]")
                .HasAnnotation("CustomSql:Raw:get_blog_name:Up", "CREATE OR ALTER PROCEDURE [get_blog_name] @id INT AS SELECT [Name] FROM [Blogs] WHERE [Id] = @id")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
>>>>>>>> 9de0344 (Updated annotation key in snapshot.):tests/EFCore.Migrations.CustomSql.Tests/MigrationTests/SqlServer/Migrations/20260501195634_Initial.Designer.cs

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore.Migrations.CustomSql.Tests.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs", t =>
                        {
                            t.HasTrigger("trg_blog_log_changes");
                        });

                    b
                        .HasAnnotation("CustomSql:Trigger:trg_blog_log_changes:Down", "DROP TRIGGER IF EXISTS [trg_blog_log_changes];")
                        .HasAnnotation("CustomSql:Trigger:trg_blog_log_changes:Up", "CREATE OR ALTER TRIGGER [trg_blog_log_changes]\r\nON [Blogs]\r\nAFTER INSERT, UPDATE\r\nAS\r\nBEGIN\r\nSET NOCOUNT ON;\r\n-- log blog insert or update\r\nEND;")
                        .HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("EFCore.Migrations.CustomSql.Tests.Models.BlogView", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("blog_view", (string)null);

                    b
                        .HasAnnotation("CustomSql:Raw:blog_view:Down", "DROP VIEW IF EXISTS blog_view")
                        .HasAnnotation("CustomSql:Raw:blog_view:Up", "CREATE VIEW blog_view AS SELECT * FROM [Blogs]");
                });

            modelBuilder.Entity("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.PostBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("PostBase");

                    b.HasDiscriminator().HasValue("PostBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EFCore.Migrations.CustomSql.Tests.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders", t =>
                        {
                            t.HasTrigger("trg_order_prevent_negative_amount");

                            t.HasTrigger("trg_order_set_confirmed");
                        });

                    b
                        .HasAnnotation("CustomSql:Trigger:trg_order_prevent_negative_amount:Down", "DROP TRIGGER IF EXISTS [trg_order_prevent_negative_amount];")
                        .HasAnnotation("CustomSql:Trigger:trg_order_prevent_negative_amount:Up", "CREATE OR ALTER TRIGGER [trg_order_prevent_negative_amount]\r\nON [Orders]\r\nAFTER UPDATE\r\nAS\r\nBEGIN\r\nSET NOCOUNT ON;\r\nIF EXISTS (SELECT 1 FROM inserted WHERE [TotalAmount] < 0)\r\n    THROW 50001, 'Amount must not be negative', 1;\r\nEND;")
                        .HasAnnotation("CustomSql:Trigger:trg_order_set_confirmed:Down", "DROP TRIGGER IF EXISTS [trg_order_set_confirmed];")
                        .HasAnnotation("CustomSql:Trigger:trg_order_set_confirmed:Up", "CREATE OR ALTER TRIGGER [trg_order_set_confirmed]\r\nON [Orders]\r\nAFTER INSERT\r\nAS\r\nBEGIN\r\nSET NOCOUNT ON;\r\nUPDATE [Orders] SET [IsConfirmed] = 0 WHERE [Id] IN (SELECT [Id] FROM inserted)\r\nEND;")
                        .HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.PostA", b =>
                {
                    b.HasBaseType("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.PostBase");

                    b.Property<string>("TextA")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("PostA");
                });

            modelBuilder.Entity("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.PostB", b =>
                {
                    b.HasBaseType("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.PostBase");

                    b.Property<string>("TextB")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("PostB");
                });
#pragma warning restore 612, 618
        }
    }
}
