// <auto-generated />
using EFCore.Migrations.CustomSql.Tests.MigrationTests.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFCore.Migrations.CustomSql.Tests.MigrationTests.PostgreSQL.Migrations
{
    [DbContext(typeof(PostgreSqlMigrationDbContext))]
    [Migration("20260430193306_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("Sql:Custom:blog_names:Down", "DROP VIEW IF EXISTS public.blog_names")
                .HasAnnotation("Sql:Custom:blog_names:Up", "CREATE OR REPLACE VIEW public.blog_names\nAS SELECT \"Id\", \"Name\" FROM \"Blogs\"")
                .HasAnnotation("Sql:Custom:get_blog_name:Down", "DROP FUNCTION IF EXISTS GetName")
                .HasAnnotation("Sql:Custom:get_blog_name:Up", "CREATE OR REPLACE FUNCTION GetName(id integer)\nRETURNS text AS $$\nBEGIN\nRETURN (SELECT \"Name\" FROM \"Blogs\" WHERE \"Id\" = id);\n END;\n$$ LANGUAGE plpgsql;")
                .HasAnnotation("Sql:Custom:get_blog_url:Down", "DROP FUNCTION IF EXISTS get_blog_url(id integer);")
                .HasAnnotation("Sql:Custom:get_blog_url:Up", "CREATE OR REPLACE FUNCTION get_blog_url(id integer)\r\nRETURNS text\r\nLANGUAGE plpgsql\r\nAS $$\r\nBEGIN\r\nRETURN (SELECT \"Name\" FROM \"Blogs\" WHERE \"Id\" = id);\r\nEND;\r\n$$;");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("BlogBaseSequence");

            modelBuilder.Entity("EFCore.Migrations.CustomSql.Tests.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b
                        .HasAnnotation("Sql:Custom:before_insert_or_update_blog:Down", "DROP FUNCTION IF EXISTS before_insert_or_update_blog() CASCADE;")
                        .HasAnnotation("Sql:Custom:before_insert_or_update_blog:Up", "CREATE OR REPLACE FUNCTION before_insert_or_update_blog()\r\nRETURNS trigger\r\nLANGUAGE plpgsql\r\nAS $$\r\nBEGIN\r\nIF NEW.\"Url\" IS NOT NULL AND NEW.\"Url\" IS DISTINCT FROM OLD.\"Url\" THEN\n    RAISE EXCEPTION 'Нельзя менять URL';\nEND IF;\nIF NEW.\"Name\" IS NOT NULL THEN\n    UPDATE \"Blogs\" SET \"Url\" = NEW.\"Url\"\n    WHERE \"Name\" = NEW.\"Name\";\nEND IF;\r\nRETURN NEW;\r\nEND;\r\n$$;\r\n\r\nCREATE TRIGGER before_insert_or_update_blog\r\nBEFORE INSERT OR UPDATE ON \"Blogs\"\r\nFOR EACH ROW\r\nEXECUTE FUNCTION before_insert_or_update_blog();");
                });

            modelBuilder.Entity("EFCore.Migrations.CustomSql.Tests.Models.BlogView", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView("blog_view", (string)null);

                    b
                        .HasAnnotation("Sql:Custom:blog_view:Down", "DROP VIEW IF EXISTS blog_view;")
                        .HasAnnotation("Sql:Custom:blog_view:Up", "CREATE OR REPLACE VIEW blog_view AS\r\nSELECT * FROM \"Blogs\";");
                });

            modelBuilder.Entity("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.ArticleBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("ArticleBase");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.BlogBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"BlogBaseSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.PostBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.ToTable("PostBase");

                    b.HasDiscriminator().HasValue("PostBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EFCore.Migrations.CustomSql.Tests.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("integer");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b
                        .HasAnnotation("Sql:Custom:prevent_update_negative_amount:Down", "DROP FUNCTION IF EXISTS prevent_update_negative_amount() CASCADE;")
                        .HasAnnotation("Sql:Custom:prevent_update_negative_amount:Up", "CREATE OR REPLACE FUNCTION prevent_update_negative_amount()\r\nRETURNS trigger\r\nLANGUAGE plpgsql\r\nAS $$\r\nBEGIN\r\nIF NEW.total_amount < 0 THEN RAISE EXCEPTION 'amount negative'; END IF;\r\nRETURN NEW;\r\nEND;\r\n$$;\r\n\r\nCREATE TRIGGER prevent_update_negative_amount\r\nBEFORE UPDATE ON \"Orders\"\r\nFOR EACH ROW\r\nEXECUTE FUNCTION prevent_update_negative_amount();")
                        .HasAnnotation("Sql:Custom:set_order_defaults:Down", "DROP FUNCTION IF EXISTS set_order_defaults() CASCADE;")
                        .HasAnnotation("Sql:Custom:set_order_defaults:Up", "CREATE OR REPLACE FUNCTION set_order_defaults()\r\nRETURNS trigger\r\nLANGUAGE plpgsql\r\nAS $$\r\nBEGIN\r\nNEW.is_confirmed = false;\r\nRETURN NEW;\r\nEND;\r\n$$;\r\n\r\nCREATE TRIGGER set_order_defaults\r\nBEFORE INSERT ON \"Orders\"\r\nFOR EACH ROW\r\nEXECUTE FUNCTION set_order_defaults();");
                });

            modelBuilder.Entity("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.ArticleA", b =>
                {
                    b.HasBaseType("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.ArticleBase");

                    b.Property<string>("ContentA")
                        .HasColumnType("text");

                    b.ToTable("ArticleA");
                });

            modelBuilder.Entity("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.ArticleB", b =>
                {
                    b.HasBaseType("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.ArticleBase");

                    b.Property<string>("ContentB")
                        .HasColumnType("text");

                    b.ToTable("ArticleB");
                });

            modelBuilder.Entity("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.BlogA", b =>
                {
                    b.HasBaseType("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.BlogBase");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.ToTable("BlogA");
                });

            modelBuilder.Entity("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.BlogB", b =>
                {
                    b.HasBaseType("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.BlogBase");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.ToTable("BlogB");
                });

            modelBuilder.Entity("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.PostA", b =>
                {
                    b.HasBaseType("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.PostBase");

                    b.Property<string>("TextA")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("PostA");
                });

            modelBuilder.Entity("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.PostB", b =>
                {
                    b.HasBaseType("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.PostBase");

                    b.Property<string>("TextB")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("PostB");
                });

            modelBuilder.Entity("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.ArticleA", b =>
                {
                    b.HasOne("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.ArticleBase", null)
                        .WithOne()
                        .HasForeignKey("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.ArticleA", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.ArticleB", b =>
                {
                    b.HasOne("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.ArticleBase", null)
                        .WithOne()
                        .HasForeignKey("EFCore.Migrations.CustomSql.Tests.Models.Inheritance.ArticleB", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
